name: insta-automation
on:
  push:
    branches: [ "main" ]  # 내 저장소의 기본 브랜치 이름이 'main'인지 확인하세요.
  workflow_dispatch:      # 수동 실행 버튼을 활성화합니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install Pillow

      - name: Run generator
        run: python src/generator.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add images/
          git commit -m "Auto-generate card" || echo "No changes to commit"
          git push
